language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-trypticon' ]; then cd .. && eval "mv $currentfolder generator-trypticon" && cd generator-trypticon; fi
